# Generated by Django 5.1.7 on 2025-03-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='static/image')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='travel.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='travel.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('questions_list', models.CharField(max_length=200)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_faq', to='travel.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title_logo_iamge', models.ImageField(upload_to='static/image')),
                ('descr', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static/image')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_intro', to='travel.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=120)),
                ('homepage_faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_questions', to='travel.homepagefaq')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageWhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/image')),
                ('map_image', models.ImageField(upload_to='static/image')),
                ('reasons_list', models.CharField(max_length=200)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_why_choose_us', to='travel.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/image')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='travel.header')),
            ],
        ),
        migrations.CreateModel(
            name='Navbars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('sub_navbar_list', models.CharField(max_length=100)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbars', to='travel.header')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('descr', models.TextField()),
                ('homepage_why_choose_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_reasons', to='travel.homepagewhychooseus')),
            ],
        ),
        migrations.CreateModel(
            name='SubnavbarsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnavbars', to='travel.navbars')),
            ],
        ),
    ]
