# Generated by Django 5.1.7 on 2025-03-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_navbars_sub_navbar_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='homepagefaq',
            name='questions_list',
        ),
    ]
