# Generated by Django 5.1.7 on 2025-03-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_homepage_lang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='homepagewhychooseus',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='homepageintro',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='homepagefaq',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='homepagequestion',
            name='homepage_faq',
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
