# Generated by Django 5.1.7 on 2025-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_header_homepage_remove_footer_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnavbarslist',
            name='url',
            field=models.CharField(max_length=30),
        ),
    ]
