# Generated by Django 5.1.7 on 2025-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_subnavbarslist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='map_image',
            field=models.URLField(),
        ),
    ]
