# Generated by Django 5.1.7 on 2025-03-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_homepagewhychooseus_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagewhychooseus',
            name='reasons_list',
        ),
        migrations.AlterField(
            model_name='reasonslist',
            name='homepage_why_choose_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons_list', to='travel.homepagewhychooseus'),
        ),
    ]
