# Generated by Django 5.1.7 on 2025-03-24 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_homepagewhychooseus_reasons_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasonslist',
            name='homepage_why_choose_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_reasons', to='travel.homepagewhychooseus'),
        ),
    ]
