# Generated by Django 5.1.7 on 2025-03-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_reasonslist_homepage_why_choose_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagelist',
            name='image',
            field=models.URLField(),
        ),
    ]
