# Generated by Django 5.1.7 on 2025-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_languagelist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='logo',
            field=models.URLField(),
        ),
    ]
