# Generated by Django 5.1.7 on 2025-03-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_header_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageList',
        ),
    ]
