# Generated by Django 5.1.7 on 2025-03-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_footer_lang_alter_footer_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='Logo',
        ),
        migrations.RemoveField(
            model_name='navbars',
            name='header',
        ),
        migrations.AlterField(
            model_name='homepageintro',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='homepageintro',
            name='title_logo_iamge',
            field=models.URLField(),
        ),
    ]
