# Generated by Django 5.1.7 on 2025-03-25 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_homepagequestion_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnavbarslist',
            name='navbar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnavbar_list', to='travel.navbars'),
        ),
    ]
