# Generated by Django 5.1.7 on 2025-03-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_alter_subnavbarslist_navbar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageintro',
            old_name='title_logo_iamge',
            new_name='title_logo_image',
        ),
    ]
