# Generated by Django 5.1.7 on 2025-03-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_rename_title_logo_iamge_homepageintro_title_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBookingSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('from_field_text', models.CharField(max_length=50)),
                ('to_field_text', models.CharField(max_length=50)),
                ('date_field_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarFieldList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=25)),
                ('departure_field_text', models.CharField(max_length=120)),
                ('return_field_text', models.CharField(max_length=255)),
                ('btn_text', models.CharField(max_length=60)),
                ('one_way_ticket_btn_text', models.CharField(max_length=255)),
                ('bookig_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_field_list', to='travel.homepagebookingsearch')),
            ],
        ),
        migrations.CreateModel(
            name='PassangerFieldList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=70)),
                ('adult_title', models.CharField(max_length=70)),
                ('adult_descr', models.CharField(max_length=255)),
                ('child_text', models.CharField(max_length=70)),
                ('child_descr', models.CharField(max_length=255)),
                ('baby_title', models.CharField(max_length=255)),
                ('baby_descr', models.CharField(max_length=255)),
                ('btn_text', models.CharField(max_length=60)),
                ('booking_search_passangers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passangers_field_list', to='travel.homepagebookingsearch')),
            ],
        ),
    ]
