# Generated by Django 5.1.7 on 2025-03-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_homepagebookingsearch_calendarfieldlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarfieldlist',
            old_name='bookig_search',
            new_name='booking_search_calendar',
        ),
        migrations.AlterField(
            model_name='calendarfieldlist',
            name='btn_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarfieldlist',
            name='departure_field_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarfieldlist',
            name='lang',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='calendarfieldlist',
            name='one_way_ticket_btn_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='calendarfieldlist',
            name='return_field_text',
            field=models.CharField(max_length=100),
        ),
    ]
