# Generated by Django 5.1.4 on 2025-03-26 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_rename_bookig_search_calendarfieldlist_booking_search_calendar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='url',
        ),
        migrations.AlterField(
            model_name='footer',
            name='lang',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='homepageintro',
            name='image',
            field=models.ImageField(upload_to='travel/static/image'),
        ),
        migrations.AlterField(
            model_name='homepageintro',
            name='title_logo_image',
            field=models.ImageField(upload_to='travel/static/image'),
        ),
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='image',
            field=models.ImageField(upload_to='travel/static/image'),
        ),
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='map_image',
            field=models.ImageField(upload_to='travel/static/image'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='travel/static/image'),
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='travel.footer')),
            ],
        ),
        migrations.CreateModel(
            name='FooterSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='travel.footer')),
            ],
        ),
    ]
