# Generated by Django 5.1.4 on 2025-03-28 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_remove_footer_title_remove_footer_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarfieldlist',
            name='btn_text',
        ),
        migrations.RemoveField(
            model_name='calendarfieldlist',
            name='one_way_ticket_btn_text',
        ),
        migrations.CreateModel(
            name='CalendarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_text', models.CharField(max_length=100)),
                ('one_way_ticket_btn_text', models.CharField(max_length=100)),
                ('search_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_calendar_list', to='travel.calendarfieldlist')),
            ],
        ),
    ]
