# Generated by Django 5.1.4 on 2025-03-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_remove_calendarfieldlist_btn_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarlist',
            name='search_calendar',
        ),
        migrations.RemoveField(
            model_name='passangerfieldlist',
            name='adult_descr',
        ),
        migrations.RemoveField(
            model_name='passangerfieldlist',
            name='adult_title',
        ),
        migrations.RemoveField(
            model_name='passangerfieldlist',
            name='baby_descr',
        ),
        migrations.RemoveField(
            model_name='passangerfieldlist',
            name='baby_title',
        ),
        migrations.RemoveField(
            model_name='passangerfieldlist',
            name='btn_text',
        ),
        migrations.RemoveField(
            model_name='passangerfieldlist',
            name='child_descr',
        ),
        migrations.RemoveField(
            model_name='passangerfieldlist',
            name='child_text',
        ),
        migrations.AddField(
            model_name='calendarlist',
            name='calendar_field',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_list', to='travel.calendarfieldlist'),
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_title', models.CharField(max_length=70)),
                ('adult_descr', models.CharField(max_length=255)),
                ('btn_text', models.CharField(max_length=60)),
                ('passanger_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adult', to='travel.passangerfieldlist')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_text', models.CharField(max_length=70)),
                ('child_descr', models.CharField(max_length=255)),
                ('passanger_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='travel.passangerfieldlist')),
            ],
        ),
    ]
