# Generated by Django 5.1.4 on 2025-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_remove_calendarlist_search_calendar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarlist',
            name='calendar_field',
        ),
        migrations.RemoveField(
            model_name='child',
            name='passanger_field',
        ),
        migrations.AddField(
            model_name='calendarfieldlist',
            name='btn_text',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AddField(
            model_name='calendarfieldlist',
            name='one_way_ticket_btn_text',
            field=models.CharField(default='Default Value', max_length=100),
        ),
        migrations.AddField(
            model_name='passangerfieldlist',
            name='adult_descr',
            field=models.CharField(default='Default adult description', max_length=255),
        ),
        migrations.AddField(
            model_name='passangerfieldlist',
            name='adult_title',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='passangerfieldlist',
            name='baby_descr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='passangerfieldlist',
            name='baby_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='passangerfieldlist',
            name='btn_text',
            field=models.CharField(default='Default Value', max_length=60),
        ),
        migrations.AddField(
            model_name='passangerfieldlist',
            name='child_descr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='passangerfieldlist',
            name='child_text',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.DeleteModel(
            name='Adult',
        ),
        migrations.DeleteModel(
            name='CalendarList',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
