# Generated by Django 5.1.4 on 2025-03-31 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_remove_calendarlist_calendar_field_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepagebookingsearch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homepagefaq',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homepageintro',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepageIntro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homepagewhychooseus',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choose_us', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='navbars',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbars', to=settings.AUTH_USER_MODEL),
        ),
    ]
