# Generated by Django 5.1.7 on 2025-04-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_rename_from_field_homepagebookingsearch_from_field_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinks',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='footersocial',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
