# Generated by Django 5.1.7 on 2025-04-05 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_alter_homepageintro_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageintro',
            name='image',
            field=models.FileField(upload_to='travel/static/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='homepageintro',
            name='title_logo_image',
            field=models.FileField(upload_to='travel/static/image'),
        ),
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='image',
            field=models.FileField(upload_to='travel/static/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='map_image',
            field=models.FileField(upload_to='travel/static/image'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.FileField(upload_to='travel/static/image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
