# Generated by Django 5.1.7 on 2025-04-05 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_alter_logo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageintro',
            name='image',
            field=models.FileField(upload_to='home_page_intro/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='homepageintro',
            name='title_logo_image',
            field=models.FileField(upload_to='home_page_intro/images/'),
        ),
    ]
