# Generated by Django 5.1.7 on 2025-04-05 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_alter_homepageintro_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='image',
            field=models.FileField(upload_to='why_choose_us/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='homepagewhychooseus',
            name='map_image',
            field=models.FileField(upload_to='why_choose_us/images/'),
        ),
    ]
