# Generated by Django 5.1.7 on 2025-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0034_alter_homepagewhychooseus_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airport_name',
            field=models.CharField(default='Unknown Airport', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='airport_short_name',
            field=models.CharField(default='Unknown short Airport', max_length=100),
        ),
    ]
