# Generated by Django 5.1.7 on 2025-04-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0035_booking_airport_name_booking_airport_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingflights',
            name='booking',
        ),
    ]
