# Generated by Django 5.1.7 on 2025-04-12 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0036_remove_bookingflights_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_here', models.CharField(max_length=120)),
                ('to_there', models.CharField(max_length=120)),
                ('airport_name', models.CharField(default='Unknown Airport', max_length=100)),
                ('airport_short_name', models.CharField(default='Unknown short Airport', max_length=100)),
                ('departure_date', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('arrive_time', models.CharField(max_length=50)),
                ('return_date', models.CharField(max_length=50)),
                ('return_departure_time', models.CharField(max_length=50)),
                ('return_arrive_time', models.CharField(max_length=50)),
                ('bort_number', models.CharField(max_length=50)),
                ('adult_count', models.CharField(max_length=50)),
                ('child_count', models.CharField(max_length=50)),
                ('baby_count', models.CharField(max_length=50)),
                ('departure_price', models.CharField(max_length=50)),
                ('return_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_flights',
        ),
        migrations.RemoveField(
            model_name='bookingpassengers',
            name='booking',
        ),
        migrations.CreateModel(
            name='PassngerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('full_name', models.CharField(max_length=60)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=20)),
                ('passport_serial', models.CharField(max_length=60)),
                ('departure_baggage_weight', models.CharField(max_length=60)),
                ('return_baggage_weight', models.CharField(max_length=60)),
                ('departure_seat_number', models.CharField(max_length=20)),
                ('return_seat_number', models.CharField(max_length=20)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasanger_list', to='travel.soldtickets')),
            ],
        ),
        migrations.DeleteModel(
            name='BookingFlights',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingPassengers',
        ),
    ]
