# Generated by Django 5.1.7 on 2025-04-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0037_soldtickets_remove_booking_booking_flights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_here', models.CharField(max_length=120)),
                ('to_there', models.CharField(max_length=120)),
                ('airport_name', models.CharField(default='Unknown Airport', max_length=100)),
                ('airport_short_name', models.CharField(default='Unknown short Airport', max_length=100)),
                ('departure_date', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('arrive_time', models.CharField(max_length=50)),
                ('return_date', models.CharField(max_length=50)),
                ('return_departure_time', models.CharField(max_length=50)),
                ('return_arrive_time', models.CharField(max_length=50)),
                ('bort_number', models.CharField(max_length=50)),
                ('departure_price', models.CharField(max_length=50)),
                ('return_price', models.CharField(max_length=50)),
                ('seats_available', models.CharField(max_length=60)),
                ('is_round_trip', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlaneSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20)),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
    ]
