# Generated by Django 5.1.7 on 2025-04-14 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0038_availabletickets_planeseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='language_list/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
            ],
        ),
    ]
