# Generated by Django 5.1.7 on 2025-04-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0039_languagelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='passngerlist',
            name='raw_passport_serial',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='passngerlist',
            name='passport_serial',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
