# Generated by Django 5.1.7 on 2025-04-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0040_passngerlist_raw_passport_serial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passngerlist',
            name='raw_passport_serial',
        ),
        migrations.AlterField(
            model_name='passngerlist',
            name='passport_serial',
            field=models.CharField(max_length=60),
        ),
    ]
