# Generated by Django 5.1.7 on 2025-04-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0042_flights_flightseats_passngers_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='departure_price',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='return_price',
        ),
    ]
