# Generated by Django 5.1.7 on 2025-04-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0044_remove_flights_arrive_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseats',
            name='seat_type',
            field=models.CharField(choices=[('departure', 'Departure'), ('return', 'Return')], default='departure', max_length=10),
        ),
    ]
