# Generated by Django 5.1.7 on 2025-04-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0045_flightseats_seat_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightseats',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.AlterField(
            model_name='flightseats',
            name='seat_type',
            field=models.CharField(choices=[('departure', 'Departure'), ('return', 'Return')], max_length=10),
        ),
    ]
