# Generated by Django 5.1.7 on 2025-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0046_rename_flight_id_flightseats_flight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='departure_date',
            field=models.CharField(default='2025-03-12', max_length=20),
        ),
        migrations.AlterField(
            model_name='flights',
            name='return_date',
            field=models.CharField(default='2025-03-12', max_length=20),
        ),
    ]
