# Generated by Django 5.1.7 on 2025-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0047_alter_flights_departure_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='return_departure_time',
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_date',
            field=models.DateField(default='2025-03-12'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='return_date',
            field=models.DateField(default='2025-03-12'),
        ),
    ]
