# Generated by Django 5.1.7 on 2025-04-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0048_remove_flights_return_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='return_date',
            field=models.DateField(),
        ),
    ]
