# Generated by Django 5.1.7 on 2025-04-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0049_alter_flights_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='adult_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='baby_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='child_count',
            field=models.IntegerField(default=0),
        ),
    ]
