# Generated by Django 5.1.7 on 2025-05-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0050_alter_tickets_adult_count_alter_tickets_baby_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='departure_baggage_weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='return_baggage_weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
