# Generated by Django 5.1.7 on 2025-05-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0051_alter_passengers_departure_baggage_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='departure_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_passengers', to='travel.flightseats'),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='return_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_passengers', to='travel.flightseats'),
        ),
    ]
