# Generated by Django 5.1.7 on 2025-05-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0052_alter_passengers_departure_seat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='return_date',
        ),
    ]
