# Generated by Django 5.1.7 on 2025-05-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0055_flightdirection_remove_tickets_adult_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
