# Generated by Django 5.1.7 on 2025-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0056_alter_tickets_ticket_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='departure_seat',
            new_name='departure_seat_id',
        ),
        migrations.RenameField(
            model_name='passengers',
            old_name='return_seat',
            new_name='return_seat_id',
        ),
        migrations.AlterField(
            model_name='flights',
            name='departure_date',
            field=models.DateField(default=''),
        ),
    ]
