# Generated by Django 5.1.7 on 2025-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0057_rename_departure_seat_passengers_departure_seat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='date_of_birth',
            field=models.DurationField(default=''),
        ),
    ]
