# Generated by Django 5.1.7 on 2025-05-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0062_alter_passengers_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='arrival_airport_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='arrival_airport_short_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='flight_airport_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='flight_ariport_short_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='flight_airport_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='languagelist',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='passangerfieldlist',
            name='passangers_field_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
