# Generated by Django 5.1.7 on 2025-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0063_flights_arrival_airport_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='arrival_airport_name',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='arrival_airport_short_name',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='flight_airport_name',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='flight_ariport_short_name',
        ),
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='arrival_airport_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='arrival_airport_short_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='flight_ariport_short_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='homepagebookingsearch',
            name='flight_airport_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
