# Generated by Django 5.1.7 on 2025-05-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0064_remove_flights_arrival_airport_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebookingsearch',
            name='arrival_airport_name',
        ),
        migrations.RemoveField(
            model_name='homepagebookingsearch',
            name='arrival_airport_short_name',
        ),
        migrations.RemoveField(
            model_name='homepagebookingsearch',
            name='flight_airport_name',
        ),
        migrations.RemoveField(
            model_name='homepagebookingsearch',
            name='flight_ariport_short_name',
        ),
    ]
