# Generated by Django 5.1.7 on 2025-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0065_remove_homepagebookingsearch_arrival_airport_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='arrival_airport_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='arrival_airport_short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
