# Generated by Django 5.1.7 on 2025-05-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0066_flights_arrival_airport_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passangerfieldlist',
            name='passangers_field_text',
        ),
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='passangers_field_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
