# Generated by Django 5.1.7 on 2025-05-13 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0067_remove_passangerfieldlist_passangers_field_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebookingsearch',
            name='passangers_field_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepageintro',
            name='title_logo_image',
            field=models.FileField(upload_to='home_page_intro/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
