# Generated by Django 5.1.7 on 2025-05-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0068_alter_homepagebookingsearch_passangers_field_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='airport_name',
            new_name='filght_airport_name',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='airport_short_name',
            new_name='flight_airport_short_name',
        ),
        migrations.AddField(
            model_name='flightdirection',
            name='filght_airport_name',
            field=models.CharField(default='Unknown Airport', max_length=100),
        ),
        migrations.AddField(
            model_name='flightdirection',
            name='flight_airport_short_name',
            field=models.CharField(default='Unknown short Airport', max_length=100),
        ),
    ]
