# Generated by Django 5.1.7 on 2025-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0070_rename_filght_airport_name_flightdirection_flight_airport_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passangerfieldlist',
            name='baby_descr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='passangerfieldlist',
            name='baby_title',
            field=models.CharField(max_length=255),
        ),
    ]
