# Generated by Django 5.1.7 on 2025-05-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0071_alter_passangerfieldlist_baby_descr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='passangers_field_text_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='select_field_text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
