# Generated by Django 5.1.7 on 2025-05-16 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0072_homepagebookingsearch_passangers_field_text_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTransContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('hading', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=90)),
                ('subheading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BaggageDescr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BaggageRowBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateDescr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CertificatesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='certificates/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('hading', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InfoForTransferContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('hading', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=90)),
                ('subheading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCheckinText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('button', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineHowDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=60)),
                ('page_text', models.CharField(max_length=120)),
                ('subheading', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='SeatChoiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SeatChoicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TopHeadingAirTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('subheading', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TopHeadingBaggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=50)),
                ('page', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TopHeadingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TopHeadingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TopHeadingOnlineReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=90)),
                ('page', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TopHeadingSeatChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=60)),
                ('page', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TopHeadingTransp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=60)),
                ('page', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TranspConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=80)),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='travel.contactinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=50)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='travel.baggagedescr')),
            ],
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('baggage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggage', to='travel.groups')),
            ],
        ),
        migrations.CreateModel(
            name='HandLuggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_luggage', to='travel.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='certificates/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('certificates_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.certificatesimages')),
            ],
        ),
        migrations.CreateModel(
            name='ListAirContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='travel.airtranscontact')),
            ],
        ),
        migrations.CreateModel(
            name='ListImportantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='travel.importantinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ListTransferInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='travel.infofortransfercontact')),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70)),
                ('online_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='travel.onlineconditions')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineInfoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('online_info_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.onlineinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('certificate_descr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='travel.certificatedescr')),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphsHowDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('online_important_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.onlineimportantinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SectionHeadingAirTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='travel.topheadingairtrans')),
            ],
        ),
        migrations.CreateModel(
            name='PathCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('top_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path', to='travel.topheadingcertificate')),
            ],
        ),
        migrations.CreateModel(
            name='TopHeadingPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('top_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path', to='travel.topheadingcontact')),
            ],
        ),
        migrations.CreateModel(
            name='TranspConditionsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('route', models.CharField(max_length=60)),
                ('transp_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.transpconditions')),
            ],
        ),
    ]
