# Generated by Django 5.1.7 on 2025-05-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0073_airtranscontact_baggagedescr_baggagerowbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraphshowdo',
            name='online_important_info',
        ),
        migrations.AddField(
            model_name='paragraphshowdo',
            name='description',
            field=models.CharField(default='description', max_length=70),
        ),
        migrations.AddField(
            model_name='paragraphshowdo',
            name='online_how_do',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='travel.onlinehowdo'),
        ),
        migrations.AddField(
            model_name='paragraphshowdo',
            name='step',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='onlinecheckintext',
            name='description',
            field=models.CharField(default='description', max_length=50),
        ),
        migrations.AlterField(
            model_name='paragraphshowdo',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='seatchoicedescription',
            name='description',
            field=models.CharField(default='description', max_length=70),
        ),
        migrations.AlterField(
            model_name='seatchoiceprice',
            name='description',
            field=models.CharField(default='description', max_length=70),
        ),
        migrations.CreateModel(
            name='ImportantInfoParagraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('online_important_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.onlineimportantinfo')),
            ],
        ),
    ]
