# Generated by Django 5.1.7 on 2025-05-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0074_remove_paragraphshowdo_online_important_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantinfo',
            old_name='hading',
            new_name='heading',
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('contact_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='travel.contactinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SupportText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('contact_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_text', to='travel.contactinfo')),
            ],
        ),
    ]
