# Generated by Django 5.1.7 on 2025-05-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0075_rename_hading_importantinfo_heading_social_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airtranscontact',
            old_name='hading',
            new_name='heading',
        ),
    ]
