# Generated by Django 5.1.7 on 2025-05-17 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0076_rename_hading_airtranscontact_heading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airtranscontact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baggage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baggages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baggagedescr',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baggage_descr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baggagerowbox',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baggage_box', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatedescr',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_descr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatesimages',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_img', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conditions',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactimages',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='handluggage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importantinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inportant_heading', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importantinfoparagraphs',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_paragraphs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infofortransfercontact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listaircontact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_air', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listimportantinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_important', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listtransferinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_list_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinecheckintext',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chekin_text', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineconditions',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_condition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinehowdo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_how_do', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineimportantinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='important_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineinfoitems',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paragraphshowdo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='how_do', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathcertificate',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_path', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatchoicedescription',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionheadingairtrans',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='social',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supporttext',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topheadingairtrans',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_heading', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topheadingbaggage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_baggages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topheadingcertificate',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_certificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topheadingcontact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_heading', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topheadingonlinereg',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_reg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topheadingpath',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topheadingseatchoice',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seatchoice', to=settings.AUTH_USER_MODEL),
        ),
    ]
