# Generated by Django 5.1.7 on 2025-05-17 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0078_seatchoiceprice_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topheadingtransp',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transpconditions',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transp_condition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transpconditionsitems',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transp_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
