# Generated by Django 5.1.7 on 2025-05-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0079_topheadingtransp_owner_transpconditions_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infofortransfercontact',
            old_name='hading',
            new_name='heading',
        ),
    ]
