# Generated by Django 5.1.7 on 2025-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0080_rename_hading_infofortransfercontact_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofortransfercontact',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
