# Generated by Django 5.1.7 on 2025-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0081_alter_infofortransfercontact_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTransPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Air Transportation Page',
                'verbose_name_plural': 'Air Transportation Page',
            },
        ),
    ]
