# Generated by Django 5.1.7 on 2025-05-18 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0082_airtranspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtranscontact',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air1', to='travel.airtranspage'),
        ),
        migrations.AddField(
            model_name='importantinfo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air5', to='travel.airtranspage'),
        ),
        migrations.AddField(
            model_name='infofortransfercontact',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air3', to='travel.airtranspage'),
        ),
        migrations.AddField(
            model_name='listaircontact',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air2', to='travel.airtranspage'),
        ),
        migrations.AddField(
            model_name='listimportantinfo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air6', to='travel.airtranspage'),
        ),
        migrations.AddField(
            model_name='listtransferinfo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air4', to='travel.airtranspage'),
        ),
        migrations.AddField(
            model_name='sectionheadingairtrans',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air9', to='travel.airtranspage'),
        ),
        migrations.AddField(
            model_name='topheadingairtrans',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air7', to='travel.airtranspage'),
        ),
    ]
