# Generated by Django 5.1.7 on 2025-05-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0083_airtranscontact_page_importantinfo_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaggagesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Air Baggage Page',
                'verbose_name_plural': 'Air Baggage Page',
            },
        ),
        migrations.AddField(
            model_name='baggage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air15', to='travel.baggagespage'),
        ),
        migrations.AddField(
            model_name='baggagedescr',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air12', to='travel.baggagespage'),
        ),
        migrations.AddField(
            model_name='baggagerowbox',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air11', to='travel.baggagespage'),
        ),
        migrations.AddField(
            model_name='groups',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air13', to='travel.baggagespage'),
        ),
        migrations.AddField(
            model_name='handluggage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air14', to='travel.baggagespage'),
        ),
    ]
