# Generated by Django 5.1.7 on 2025-05-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0084_baggagespage_baggage_page_baggagedescr_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Certificate Page',
                'verbose_name_plural': 'Certificate Page',
            },
        ),
        migrations.AddField(
            model_name='certificatedescr',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air18', to='travel.certificatepage'),
        ),
        migrations.AddField(
            model_name='certificatesimages',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air20', to='travel.certificatepage'),
        ),
        migrations.AddField(
            model_name='image',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air21', to='travel.certificatepage'),
        ),
        migrations.AddField(
            model_name='paragraphs',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air19', to='travel.certificatepage'),
        ),
        migrations.AddField(
            model_name='pathcertificate',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air17', to='travel.certificatepage'),
        ),
        migrations.AddField(
            model_name='topheadingcertificate',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air16', to='travel.certificatepage'),
        ),
    ]
