# Generated by Django 5.1.7 on 2025-05-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0085_certificatepage_certificatedescr_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'HeadContact Page',
                'verbose_name_plural': 'HeadContact Page',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air26', to='travel.headcontactpage'),
        ),
        migrations.AddField(
            model_name='contactimages',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air24', to='travel.headcontactpage'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air25', to='travel.headcontactpage'),
        ),
        migrations.AddField(
            model_name='social',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air27', to='travel.headcontactpage'),
        ),
        migrations.AddField(
            model_name='supporttext',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air28', to='travel.headcontactpage'),
        ),
        migrations.AddField(
            model_name='topheadingcontact',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air22', to='travel.headcontactpage'),
        ),
        migrations.AddField(
            model_name='topheadingpath',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air23', to='travel.headcontactpage'),
        ),
    ]
