# Generated by Django 5.1.7 on 2025-05-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0086_headcontactpage_contact_page_contactimages_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineRegistrationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'OnlineRegistration Page',
                'verbose_name_plural': 'OnlineRegistration Page',
            },
        ),
        migrations.AddField(
            model_name='conditions',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air43', to='travel.onlineregistrationpage'),
        ),
        migrations.AddField(
            model_name='importantinfoparagraphs',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air47', to='travel.onlineregistrationpage'),
        ),
        migrations.AddField(
            model_name='onlinecheckintext',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air41', to='travel.onlineregistrationpage'),
        ),
        migrations.AddField(
            model_name='onlineconditions',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air42', to='travel.onlineregistrationpage'),
        ),
        migrations.AddField(
            model_name='onlinehowdo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air44', to='travel.onlineregistrationpage'),
        ),
        migrations.AddField(
            model_name='onlineimportantinfo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air46', to='travel.onlineregistrationpage'),
        ),
        migrations.AddField(
            model_name='onlineinfo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air50', to='travel.onlineregistrationpage'),
        ),
        migrations.AddField(
            model_name='onlineinfoitems',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air49', to='travel.onlineregistrationpage'),
        ),
        migrations.AddField(
            model_name='paragraphshowdo',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air45', to='travel.onlineregistrationpage'),
        ),
    ]
