# Generated by Django 5.1.7 on 2025-05-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0088_topheadingonlinereg_page2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatChoicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'SeatChoice Page',
                'verbose_name_plural': 'SeatChoice Page',
            },
        ),
        migrations.CreateModel(
            name='TransportConditionalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'TransportConditional Page',
                'verbose_name_plural': 'TransportConditional Page',
            },
        ),
        migrations.AddField(
            model_name='seatchoicedescription',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air50', to='travel.seatchoicepage'),
        ),
        migrations.AddField(
            model_name='seatchoiceprice',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air52', to='travel.seatchoicepage'),
        ),
        migrations.AddField(
            model_name='transpconditions',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air57', to='travel.transportconditionalpage'),
        ),
        migrations.AddField(
            model_name='transpconditionsitems',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air58', to='travel.transportconditionalpage'),
        ),
    ]
