# Generated by Django 5.1.7 on 2025-05-18 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0089_seatchoicepage_transportconditionalpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topheadingseatchoice',
            name='page10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air51', to='travel.seatchoicepage'),
        ),
        migrations.AddField(
            model_name='topheadingtransp',
            name='page6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air56', to='travel.transportconditionalpage'),
        ),
    ]
