# Generated by Django 5.1.7 on 2025-05-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0090_topheadingseatchoice_page10_topheadingtransp_page6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listimportantinfo',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='travel.importantinfo'),
        ),
        migrations.AlterField(
            model_name='sectionheadingairtrans',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='travel.topheadingairtrans'),
        ),
    ]
