# Generated by Django 5.1.7 on 2025-05-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0091_alter_listimportantinfo_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaircontact',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='travel.airtranscontact'),
        ),
        migrations.AlterField(
            model_name='listtransferinfo',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='travel.infofortransfercontact'),
        ),
    ]
