# Generated by Django 5.1.7 on 2025-05-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0092_alter_listaircontact_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphs',
            name='certificate_descr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='travel.certificatedescr'),
        ),
        migrations.AlterField(
            model_name='pathcertificate',
            name='top_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path', to='travel.topheadingcertificate'),
        ),
    ]
