# Generated by Django 5.1.7 on 2025-05-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0093_alter_paragraphs_certificate_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='certificates_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.certificatesimages'),
        ),
    ]
