# Generated by Django 5.1.7 on 2025-05-18 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0094_alter_image_certificates_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baggage',
            name='baggage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baggage', to='travel.groups'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='travel.baggagedescr'),
        ),
        migrations.AlterField(
            model_name='handluggage',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_luggage', to='travel.groups'),
        ),
    ]
