# Generated by Django 5.1.7 on 2025-05-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0095_alter_baggage_baggage_alter_groups_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='online_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='travel.onlineconditions'),
        ),
        migrations.AlterField(
            model_name='importantinfoparagraphs',
            name='online_important_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.onlineimportantinfo'),
        ),
        migrations.AlterField(
            model_name='onlineinfoitems',
            name='online_info_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.onlineinfo'),
        ),
        migrations.AlterField(
            model_name='paragraphshowdo',
            name='online_how_do',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='travel.onlinehowdo'),
        ),
        migrations.AlterField(
            model_name='social',
            name='contact_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social', to='travel.contactinfo'),
        ),
        migrations.AlterField(
            model_name='supporttext',
            name='contact_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_text', to='travel.contactinfo'),
        ),
        migrations.AlterField(
            model_name='topheadingpath',
            name='top_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path', to='travel.topheadingcontact'),
        ),
        migrations.AlterField(
            model_name='transpconditionsitems',
            name='transp_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.transpconditions'),
        ),
    ]
