# Generated by Django 5.1.7 on 2025-05-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0096_alter_conditions_online_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtranscontact',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
