# Generated by Django 5.1.7 on 2025-05-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0097_alter_airtranscontact_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseats',
            name='hold_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flightseats',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
