# Generated by Django 5.1.7 on 2025-05-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0099_airport_ticket_flight_seat_payment_passenger_charge_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agency',
            new_name='AgencyPdf',
        ),
        migrations.RenameModel(
            old_name='Airport',
            new_name='AirportPdf',
        ),
        migrations.RenameModel(
            old_name='Flight',
            new_name='FlightPdf',
        ),
        migrations.RenameModel(
            old_name='Passenger',
            new_name='PassengerPdf',
        ),
        migrations.RenameModel(
            old_name='Seat',
            new_name='SeatPdf',
        ),
        migrations.RenameModel(
            old_name='Ticket',
            new_name='TicketPdf',
        ),
    ]
