# Generated by Django 5.1.7 on 2025-05-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0100_rename_agency_agencypdf_rename_airport_airportpdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDirectionPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot', models.CharField(default='ՈՏՔ', max_length=150)),
                ('date', models.DateTimeField()),
                ('fligth', models.CharField(max_length=80)),
                ('flight_start', models.CharField(max_length=100)),
                ('flight_end', models.CharField(max_length=180)),
                ('plan', models.CharField(max_length=140)),
                ('status', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PassangersPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passangers_title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=10)),
                ('passport_serial', models.CharField(max_length=50)),
                ('seat', models.CharField(max_length=50)),
                ('ticket', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerCountPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('adult', models.CharField(max_length=100)),
                ('child', models.CharField(max_length=100)),
                ('baby', models.CharField(max_length=20)),
                ('text', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50)),
                ('po_number', models.CharField(max_length=100)),
                ('payer_name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('transaction_date', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RezervPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezerv_heading', models.CharField(max_length=50)),
                ('rezerv', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Պայմաններ և դրույթներ', max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flightpdf',
            name='to_there',
        ),
        migrations.RemoveField(
            model_name='flightpdf',
            name='from_here',
        ),
        migrations.RemoveField(
            model_name='seatpdf',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='passengerpdf',
            name='departure_seat',
        ),
        migrations.RemoveField(
            model_name='passengerpdf',
            name='return_seat',
        ),
        migrations.RemoveField(
            model_name='passengerpdf',
            name='ticket',
        ),
        migrations.AlterField(
            model_name='charge',
            name='passenger',
            field=models.CharField(max_length=160),
        ),
        migrations.RemoveField(
            model_name='charge',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ticket',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payer_name',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='po_number',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='vat',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='leg_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='charge',
            name='foot',
            field=models.CharField(default='ՈՏՔ', max_length=160),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay',
            field=models.CharField(default='15', max_length=200),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='date_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TermItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('heading', models.CharField(max_length=255)),
                ('details', models.TextField(help_text='Use <br/> to separate lines if needed.')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.termsandconditions')),
            ],
        ),
        migrations.CreateModel(
            name='BaggagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ուղեբեռի թույլտվություն', max_length=255)),
                ('description', models.TextField()),
                ('terms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baggage_policy', to='travel.termsandconditions')),
            ],
        ),
        migrations.DeleteModel(
            name='AgencyPdf',
        ),
        migrations.DeleteModel(
            name='AirportPdf',
        ),
        migrations.DeleteModel(
            name='FlightPdf',
        ),
        migrations.DeleteModel(
            name='SeatPdf',
        ),
        migrations.DeleteModel(
            name='PassengerPdf',
        ),
        migrations.DeleteModel(
            name='TicketPdf',
        ),
    ]
