# Generated by Django 5.1.7 on 2025-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0101_flightdirectionpdf_headerpdf_passangerspdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdirectionpdf',
            name='title',
            field=models.CharField(default='Ուղևորներ', max_length=30),
        ),
        migrations.AlterField(
            model_name='flightdirectionpdf',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
