# Generated by Django 5.1.7 on 2025-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0102_flightdirectionpdf_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengercountpdf',
            name='baby',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='passengercountpdf',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
