# Generated by Django 5.1.7 on 2025-05-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0103_alter_passengercountpdf_baby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='amount',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='charge',
            name='total',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='charge',
            name='vat',
            field=models.CharField(max_length=12),
        ),
    ]
