# Generated by Django 5.1.7 on 2025-05-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0104_alter_charge_amount_alter_charge_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLi1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='1․ Ավիափոխադրողի կողմից չվերթի չեղարկման դեպքում՝', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLi2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='2․ Ուղևորի նախաձեռնությամբ ավիատոմսի վերադարձ կամ վերաձևակերպում՝', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLi3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='3․ 14 տարին չլրացած երեխաների փոխադրումը կատարվում է ծնողի կամ ծնողի կողմից նոտարական', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='charge',
            name='title',
            field=models.CharField(default='Գանձումները', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='title',
            field=models.CharField(default='Վճարման մասին տեղեկատվություն', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.CharField(blank=True, default='Ընդամենը', max_length=100),
        ),
        migrations.DeleteModel(
            name='TermItem',
        ),
    ]
