# Generated by Django 5.1.7 on 2025-05-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0105_itemli1_itemli2_itemli3_charge_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baggagepolicy',
            name='terms',
        ),
    ]
