# Generated by Django 5.1.7 on 2025-05-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0106_remove_baggagepolicy_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaggagePolicy',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.DeleteModel(
            name='FlightDirectionPdf',
        ),
        migrations.DeleteModel(
            name='HeaderPdf',
        ),
        migrations.DeleteModel(
            name='ItemLi1',
        ),
        migrations.DeleteModel(
            name='ItemLi2',
        ),
        migrations.DeleteModel(
            name='ItemLi3',
        ),
        migrations.DeleteModel(
            name='PassangersPdf',
        ),
        migrations.DeleteModel(
            name='PassengerCountPdf',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
        migrations.DeleteModel(
            name='RezervPdf',
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
    ]
