# Generated by Django 5.1.7 on 2025-05-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0108_flightschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCheckBaggagePageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('passanger_types', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('baggage_weights', models.CharField(max_length=100)),
                ('direction_warning_text', models.CharField(max_length=120)),
                ('add_btn_text', models.CharField(max_length=120)),
                ('remove_btn_text', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BookingClientInfoPageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('passanger_types', models.CharField(max_length=120)),
                ('order_data_title', models.CharField(max_length=120)),
                ('visitor_details_title', models.CharField(max_length=120)),
                ('seat_title', models.CharField(max_length=120)),
                ('phone_text_field', models.CharField(max_length=120)),
                ('email_text_field', models.CharField(max_length=120)),
                ('title_text_field', models.CharField(max_length=120)),
                ('title_select', models.CharField(max_length=120)),
                ('full_name_text_field', models.CharField(max_length=120)),
                ('birth_text_field', models.CharField(max_length=120)),
                ('citizenship_text_field', models.CharField(max_length=120)),
                ('passport_text_field', models.CharField(max_length=120)),
                ('select_btn_text', models.CharField(max_length=120)),
                ('selected_btn_text', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BookingNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('section_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPaymentPageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('credit_card_text', models.CharField(max_length=120)),
                ('privacy_notice_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingResultsPageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('navigation', models.CharField(max_length=120)),
                ('hours_mins_text', models.CharField(max_length=220)),
                ('transit_text', models.CharField(max_length=250)),
                ('select_btn_text', models.CharField(max_length=120)),
                ('selected_btn_text', models.CharField(max_length=120)),
                ('continue_btn_text', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('sub_total_text_field', models.CharField(max_length=120)),
                ('quantity_text_field', models.CharField(max_length=120)),
                ('seat_text_field', models.CharField(max_length=100)),
                ('total_text_field', models.CharField(max_length=100)),
            ],
        ),
    ]
