# Generated by Django 5.1.7 on 2025-05-27 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0109_bookingcheckbaggagepagelabel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcheckbaggagepagelabel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_baggage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingclientinfopagelabel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingnavigation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingpaymentpagelabel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyment_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingresultspagelabel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_sum', to=settings.AUTH_USER_MODEL),
        ),
    ]
