# Generated by Django 5.1.7 on 2025-05-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0110_bookingcheckbaggagepagelabel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='total_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
