# Generated by Django 5.1.7 on 2025-05-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0112_remove_importantinfoparagraphs_online_important_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transpconditions',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transpconditions',
            name='page',
        ),
        migrations.RemoveField(
            model_name='transpconditionsitems',
            name='transp_items',
        ),
        migrations.RemoveField(
            model_name='transpconditionsitems',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transpconditionsitems',
            name='page',
        ),
        migrations.DeleteModel(
            name='TopHeadingTransp',
        ),
        migrations.DeleteModel(
            name='TranspConditions',
        ),
        migrations.DeleteModel(
            name='TranspConditionsItems',
        ),
    ]
