# Generated by Django 5.1.7 on 2025-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0113_remove_transpconditions_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebookingsearch',
            name='search_btn_text',
            field=models.CharField(default='search', max_length=90),
        ),
    ]
