# Generated by Django 5.1.7 on 2025-05-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0114_homepagebookingsearch_search_btn_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebookingsearch',
            name='search_btn_text',
            field=models.CharField(default='Search', max_length=90),
        ),
    ]
