# Generated by Django 5.1.7 on 2025-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0115_alter_homepagebookingsearch_search_btn_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldFlightArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('flight_from', models.CharField(max_length=120)),
                ('flight_to', models.CharField(max_length=120)),
                ('flight_date', models.DateField()),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('bort_number', models.CharField(max_length=50)),
                ('total_passengers', models.IntegerField()),
                ('total_price', models.CharField(blank=True, max_length=30, null=True)),
                ('passengers_data', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='btn_text',
            field=models.CharField(default='countinue/pay', max_length=100),
        ),
    ]
