# Generated by Django 5.1.7 on 2025-05-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0116_soldflightarchive_ordersummary_btn_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldflightarchive',
            name='ticket_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldflightarchive',
            name='ticket_is_sold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soldflightarchive',
            name='ticket_number',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='soldflightarchive',
            name='ticket_price',
            field=models.CharField(default='20000', max_length=50),
        ),
        migrations.AddField(
            model_name='soldflightarchive',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='soldflightarchive',
            name='ticket_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
