# Generated by Django 5.1.7 on 2025-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0117_soldflightarchive_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseats',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
