# Generated by Django 5.1.7 on 2025-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0118_flightseats_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightseats',
            old_name='price',
            new_name='departure_price',
        ),
        migrations.AddField(
            model_name='flightseats',
            name='return_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
