# Generated by Django 5.1.7 on 2025-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0119_rename_price_flightseats_departure_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='total_price',
        ),
        migrations.AddField(
            model_name='soldflightarchive',
            name='baby_price',
            field=models.CharField(default='9000', max_length=50),
        ),
        migrations.AddField(
            model_name='tickets',
            name='baby_price',
            field=models.CharField(default='9000', max_length=50),
        ),
    ]
