# Generated by Django 5.1.7 on 2025-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0120_remove_soldflightarchive_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='adult_price',
            field=models.CharField(default='20000', max_length=50),
        ),
        migrations.AddField(
            model_name='tickets',
            name='child_price',
            field=models.CharField(default='5000', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='baby_price',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
