# Generated by Django 5.1.7 on 2025-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0123_alter_soldflightarchive_adult_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='adult_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='child_price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
