# Generated by Django 5.1.7 on 2025-05-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0124_alter_tickets_adult_price_alter_tickets_child_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='adult_price',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='baby_price',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='child_price',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
