# Generated by Django 5.1.7 on 2025-05-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0126_alter_tickets_adult_price_alter_tickets_baby_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengersPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.CharField(default='20000', max_length=50)),
                ('child_price', models.CharField(default='10000', max_length=50)),
                ('baby_price', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='passengers',
            name='passenger_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('baby', 'Baby')], default='adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='adult_price',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='baby_price',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='child_price',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
