# Generated by Django 5.1.7 on 2025-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0127_passengersprice_passengers_passenger_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_round_trip', models.BooleanField(default=False)),
                ('from_here', models.CharField(max_length=100)),
                ('to_there', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adult_count', models.PositiveIntegerField(default=1)),
                ('child_count', models.PositiveIntegerField(default=0)),
                ('baby_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
