# Generated by Django 5.1.7 on 2025-05-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0129_ticketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschedule',
            name='arrival_time',
            field=models.CharField(default='00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='flightschedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='travel.flights'),
        ),
        migrations.DeleteModel(
            name='BookingCheckBaggagePageLabel',
        ),
    ]
