# Generated by Django 5.1.7 on 2025-05-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0130_flightschedule_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='adult_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='baby_price',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='child_price',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
