# Generated by Django 5.1.7 on 2025-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0132_bookingclientinfopagelabel_baggage_airport_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_type',
            field=models.CharField(choices=[('one-way', 'One Way'), ('round-trip', 'Round Trip')], default='one-way', max_length=20),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='departure_baggage_weight',
            field=models.CharField(default='10', max_length=20),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='return_baggage_weight',
            field=models.CharField(default='10', max_length=20),
        ),
    ]
