# Generated by Django 5.1.7 on 2025-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0133_passengers_price_tickets_ticket_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldFlightArchive',
        ),
        migrations.AlterField(
            model_name='passengers',
            name='departure_baggage_weight',
            field=models.CharField(blank=True, default='10', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='return_baggage_weight',
            field=models.CharField(blank=True, default='10', max_length=20, null=True),
        ),
    ]
