# Generated by Django 5.1.7 on 2025-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0134_delete_soldflightarchive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
