# Generated by Django 5.1.7 on 2025-06-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0135_alter_passengers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='page',
        ),
        migrations.RemoveField(
            model_name='handluggage',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='baggage',
            name='baggage',
        ),
        migrations.DeleteModel(
            name='BaggageDescr',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
