# Generated by Django 5.1.7 on 2025-06-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0136_remove_groups_groups_remove_groups_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baggagerowbox',
            name='text',
            field=models.TextField(),
        ),
    ]
