# Generated by Django 5.1.7 on 2025-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0137_alter_baggagerowbox_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingclientinfopagelabel',
            name='passport_validity_period_field',
            field=models.CharField(default='The passport is valid until', max_length=120),
        ),
    ]
