# Generated by Django 5.1.7 on 2025-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0138_bookingclientinfopagelabel_passport_validity_period_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='passport_validity_period',
            field=models.CharField(default='write passport date', max_length=60),
        ),
    ]
