# Generated by Django 5.1.7 on 2025-06-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0139_passengers_passport_validity_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passport_validity_period',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
