# Generated by Django 5.1.7 on 2025-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0140_alter_passengers_passport_validity_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldFlightArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('flight_from', models.CharField(max_length=120)),
                ('flight_to', models.CharField(max_length=120)),
                ('flight_departure_date', models.DateField()),
                ('flight_return_date', models.DateField()),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('bort_number', models.CharField(max_length=50)),
                ('total_passengers', models.IntegerField()),
                ('total_price', models.CharField(blank=True, max_length=30, null=True)),
                ('passengers_data', models.JSONField()),
                ('passport_serial', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('ticket_number', models.CharField(default='0000000', max_length=100)),
                ('ticket_price', models.CharField(max_length=100)),
                ('adult_price', models.CharField(blank=True, max_length=50, null=True)),
                ('child_price', models.CharField(blank=True, max_length=50, null=True)),
                ('baby_price', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ticket_is_sold', models.BooleanField(default=True)),
            ],
        ),
    ]
