# Generated by Django 5.1.7 on 2025-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0141_soldflightarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldflightarchive',
            name='flight_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldflightarchive',
            name='flight_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
