# Generated by Django 5.1.7 on 2025-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0142_alter_soldflightarchive_flight_departure_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsDescr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=60)),
                ('descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsTopHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=15)),
                ('section', models.CharField(max_length=60)),
                ('page', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ContactIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=60)),
                ('img_url', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactNewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=60)),
                ('descr', models.TextField()),
                ('img_url', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TopContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=15)),
                ('section', models.CharField(max_length=60)),
                ('page', models.CharField(max_length=120)),
            ],
        ),
    ]
