# Generated by Django 5.1.7 on 2025-06-18 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0143_aboutusdescr_aboutustopheading_contactintro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusdescr',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aboutus_descriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aboutustopheading',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactintro',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmap',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactnewinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topcontact',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topContact', to=settings.AUTH_USER_MODEL),
        ),
    ]
