# Generated by Django 5.1.7 on 2025-06-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0144_aboutusdescr_owner_aboutustopheading_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionheadingairtrans',
            name='page',
        ),
        migrations.RemoveField(
            model_name='airtranscontact',
            name='page',
        ),
        migrations.RemoveField(
            model_name='listtransferinfo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='listaircontact',
            name='page',
        ),
        migrations.RemoveField(
            model_name='importantinfo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='infofortransfercontact',
            name='page',
        ),
        migrations.RemoveField(
            model_name='listimportantinfo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='topheadingairtrans',
            name='page',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='baby_price',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='bort_number',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='child_price',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='passport_serial',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='ticket_is_sold',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='ticket_number',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='soldflightarchive',
            name='ticket_type',
        ),
        migrations.DeleteModel(
            name='AirTransPage',
        ),
    ]
