# Generated by Django 5.1.7 on 2025-06-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0145_remove_sectionheadingairtrans_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldflightarchive',
            name='seats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldflightarchive',
            name='ticket_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
