# Generated by Django 5.1.7 on 2025-06-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0146_soldflightarchive_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_type',
            field=models.CharField(choices=[('one-way', 'One Way'), ('round-trip', 'Round Trip')], max_length=20),
        ),
    ]
