# Generated by Django 5.1.7 on 2025-06-25 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0148_auto_20250624_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightseats',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_seats', to='travel.flights'),
        ),
    ]
