# Generated by Django 5.1.7 on 2025-06-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0149_alter_flightseats_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passengers',
            old_name='full_name',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='passengers',
            name='name',
            field=models.CharField(default='add name', max_length=100),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
