# Generated by Django 5.1.7 on 2025-06-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0150_rename_full_name_passengers_surname_passengers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengersprice',
            name='baby_price',
            field=models.CharField(default='5000', max_length=50),
        ),
    ]
